Fix building the project
`ghcid` with `stack ghci` worked fine, but `stack build` complained:

```
~/proj/haskell/rbdb/src/Main.hs:64:5: error:
    • Non type-variable argument in the constraint: Show (Token s)
    • When checking the inferred type
        showError :: forall {s}.
                     Show (Token s) =>
                     Text.Megaparsec.Error.ParseError s Void -> String
      In an equation for ‘showErrorBundle’:
          showErrorBundle ParseErrorBundle {bundleErrors}
            = unlines (showError <$> NE.toList bundleErrors)
            where
                showError (TrivialError pos maybeUnexpectedToken expectedTokens)
                  = mconcat
                      ["Error at byte 0x"
                         <> showHex pos "" <> " (" <> show pos <> "):\n  ",
                       ....]
                showError (FancyError pos fancyErrors)
                  = mconcat
                      ["Error at byte 0x"
                         <> showHex pos "" <> " (" <> show pos <> "):\n  ",
                       ....]
                showErrorItem (Tokens ts)
                  = intercalate ", " $ show <$> NE.toList ts
                showErrorItem (Label cs) = NE.toList cs
                showErrorItem EndOfInput = "EndOfInput"
                showErrorFancy (ErrorFail s) = s
                showErrorFancy (ErrorIndentation {})
                  = error "Unexpected indentation error"
                showErrorFancy (ErrorCustom e) = absurd e
    Suggested fix: Perhaps you intended to use FlexibleContexts
   |
64 |     showError (TrivialError pos maybeUnexpectedToken expectedTokens) = mconcat
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

I don't understand what it wants given that my `ParseError` is a
concrete type. Renaming it (to avoid the conflict with `megaparsec`'s
`ParseError`) didn't help.